import { DataCard } from '../data-card';

export const supporters: DataCard[] = [
  { title: 'Назар Дейнега', status: 'element' },
  { title: 'Stanislav Tyrinov', status: 'element' },
  { title: 'Андрій Максимів', status: 'element' },
  { title: 'Уляна Тесля', status: 'element' },
  { title: 'Олександр Красновський', status: 'element' },
  { title: 'Eugene Ermolenkoe', status: 'element' },
  { title: 'Влад Оксентюк', status: 'element' },
  { title: 'Марина Янул', status: 'element' },
  { title: 'Віталій Станко', status: 'element' },
  { title: 'Сергій Нітченко', status: 'element' },
  { title: 'Alex Fox', status: 'element' },
  { title: 'Антон Шумський', status: 'element' },
  { title: 'Діана Колісніченко', status: 'element' },
  { title: 'Nikolay Chermyanin', status: 'element' },
  { title: 'Ілля Хромов', status: 'element' },
  { title: 'Dzianis Pryshchep', status: 'element' },
  { title: 'Ігор Небещенко', status: 'element' },
  { title: 'Роман Олійник', status: 'element' },
  { title: 'Артем Репніков', status: 'element' },
  { title: 'Родіон Долгий', status: 'element' },
  { title: 'Андрій Вербенець', status: 'element' },
  { title: 'Андріан Кобевко', status: 'element' },
  { title: 'Олег Пухальський', status: 'element' },
  { title: 'Александр Гуков', status: 'element' },
  { title: 'Євген Кривонос', social: { fb: '' }, status: 'classname' },
  { title: 'Віктор Кениз', social: { fb: '' }, status: 'classname' },
  { title: 'Артём Кобзарь', social: { fb: '' }, status: 'id', img: '' },
  { title: 'Ткаченко Віктор', social: { fb: '' }, status: 'id', img: '' },
  { title: 'Оксана Минеева', social: { fb: '' }, status: 'inline', img: '' },
];
